service: qleetus

provider:
  name: aws
  runtime: nodejs10.x
  environment: 
    DB_TABLENAME: ${file(./.env.json):DB_TABLENAME}

functions:
  app:
    handler: handler.appHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'